from bot.dispatcher import dp
from bot.handler.main import *
from bot.handler.renter import *
from bot.handler.owner import *
from bot.handler.settings import *
from bot.handler.apartment import *
from bot.handler.searchapart import *
from bot.handler.likedaparts import *
from bot.handler.myaparts import *